version: 2
updates:
- package-ecosystem: npm
  directory: "/driver"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: rpc-websockets
    versions:
    - 7.4.8
    - 7.4.9
  - dependency-name: appium-base-driver
    versions:
    - 7.4.1
    - 7.4.2
    - 7.5.0
    - 7.5.1
- package-ecosystem: npm
  directory: "/example/nodejs"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webdriverio
    versions:
    - 6.12.1
    - 7.0.4
    - 7.0.7
    - 7.0.9
    - 7.1.1
    - 7.2.2
    - 7.2.3
    - 7.3.0
    - 7.3.1
    - 7.4.6
- package-ecosystem: npm
  directory: "/finder/nodejs"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.35
    - 14.14.37
    - 14.14.41
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
